apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: database
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  PMA_HOST: mysql
  PMA_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK #password
  MYSQL_DATABASE: ZGF0YWJhc2UK #database
  MYSQL_USER: cm9vdAo= #root
  MYSQL_PASSWORD: cGFzc3dvcmQK #password

