apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  PMA_HOST: mysql
  PMA_PORT: 3306
  PMA_USER: root
  MYSQL_USERNAME: root
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: opaque
data:
  
